version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Instalando dependências...
      - npm install
  build:
    commands:
      - echo Gerando build do Angular...
      - npm run build -- --configuration=production
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/s3-angular-project/browser'
